import { jsPDF } from "jspdf";
import { CalendarImage, MONTHS, CalendarStyleId } from "../types";
import { REFERENCE_WIDTH, REFERENCE_HEIGHT } from "./canvasHelper";

export const generateCalendarPDF = (images: CalendarImage[], theme: string, styleId: CalendarStyleId = 'classic'): void => {
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4"
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const year = new Date().getFullYear(); 

  images.forEach((imgData, index) => {
    if (index > 0) doc.addPage();

    // 1. Draw Image
    try {
      const imgProps = doc.getImageProperties(`data:image/png;base64,${imgData.base64}`);
      const imgRatio = imgProps.width / imgProps.height;
      const pageRatio = pageWidth / pageHeight;

      let baseWidth, baseHeight, baseX, baseY;

      if (imgRatio > pageRatio) {
        baseHeight = pageHeight;
        baseWidth = pageHeight * imgRatio;
        baseX = (pageWidth - baseWidth) / 2;
        baseY = 0;
      } else {
        baseWidth = pageWidth;
        baseHeight = pageWidth / imgRatio;
        baseX = 0;
        baseY = (pageHeight - baseHeight) / 2;
      }

      let finalX = baseX, finalY = baseY, finalW = baseWidth, finalH = baseHeight;

      if (imgData.layout) {
        const { x, y, scale } = imgData.layout.image;
        finalW = baseWidth * scale;
        finalH = baseHeight * scale;
        const scaleOffsetX = (finalW - baseWidth) / 2;
        const scaleOffsetY = (finalH - baseHeight) / 2;
        const conversionFactor = pageWidth / REFERENCE_WIDTH;
        const mmX = x * conversionFactor;
        const mmY = y * conversionFactor;
        finalX = baseX + mmX - scaleOffsetX;
        finalY = baseY + mmY - scaleOffsetY;
      }

      let imageOpacity = 1;
      if (imgData.layout?.image?.opacity !== undefined) {
        imageOpacity = imgData.layout.image.opacity;
      }

      if (imageOpacity < 1) {
        doc.setGState(new doc.GState({ opacity: imageOpacity }));
      }

      doc.addImage(`data:image/png;base64,${imgData.base64}`, 'PNG', finalX, finalY, finalW, finalH, undefined, 'FAST');

      if (imageOpacity < 1) {
        doc.setGState(new doc.GState({ opacity: 1 }));
      }

      if (imgData.layout?.cutout?.enabled && imgData.layout.cutout.data) {
        const cutoutSize = Math.min(pageWidth, pageHeight) * 0.45 * imgData.layout.cutout.scale;
        const conversionFactor = pageWidth / REFERENCE_WIDTH;
        const cutoutX = pageWidth / 2 + imgData.layout.cutout.x * conversionFactor - cutoutSize / 2;
        const cutoutY = pageHeight / 2 + imgData.layout.cutout.y * conversionFactor - cutoutSize / 2;

        if (imgData.layout.cutout.opacity < 1) {
          doc.setGState(new doc.GState({ opacity: imgData.layout.cutout.opacity }));
        }

        doc.addImage(imgData.layout.cutout.data, 'PNG', cutoutX, cutoutY, cutoutSize, cutoutSize, undefined, 'FAST', imgData.layout.cutout.rotation);

        if (imgData.layout.cutout.opacity < 1) {
          doc.setGState(new doc.GState({ opacity: 1 }));
        }
      }
    } catch (e) {
      console.error('Error adding image to PDF', e);
    }

    // 2. Render Style
    // Note: Complex canvas styles (glass, circular) are approximated in PDF or default to standard.
    let offsetX = 0;
    let offsetY = 0;
    if (imgData.layout) {
        const conversionFactor = pageWidth / REFERENCE_WIDTH;
        offsetX = imgData.layout.overlay.x * conversionFactor;
        offsetY = imgData.layout.overlay.y * conversionFactor;
    }

    if (styleId === 'sidebar') {
        renderSidebarPDF(doc, imgData.month, year, pageWidth, pageHeight, offsetX, offsetY);
    } else if (styleId === 'minimal_bottom') {
        renderMinimalPDF(doc, imgData.month, year, pageWidth, pageHeight, offsetX, offsetY);
    } else if (styleId === 'header_grid') {
        renderHeaderGridPDF(doc, imgData.month, year, pageWidth, pageHeight, offsetX, offsetY);
    } else {
        // Fallback for complex styles (Glass, Circular, Cards, BigDate) -> Use Classic style in PDF for readability
        renderStandardPDF(doc, imgData.month, year, theme, pageWidth, pageHeight, offsetX, offsetY);
    }

    doc.setFontSize(8);
    doc.setTextColor(200, 200, 200);
    doc.text(`Generated by ThemeCalendar AI`, pageWidth - 10, pageHeight - 5, { align: "right" });
  });

  doc.save(`${theme.replace(/\s+/g, '_')}_Calendar.pdf`);
};

const renderStandardPDF = (doc: jsPDF, month: string, year: number, theme: string, pW: number, pH: number, offX: number, offY: number) => {
    const overlayHeight = pH * 0.4; 
    const baseOverlayY = pH - overlayHeight;
    const overlayX = offX;
    const overlayY = baseOverlayY + offY;

    doc.setFillColor(15, 23, 42); 
    doc.rect(overlayX, overlayY, pW, overlayHeight, "F");

    const padding = pW * 0.05;
    
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(36); 
    doc.text(month.toUpperCase(), padding + overlayX, overlayY + 25);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(16);
    doc.setTextColor(148, 163, 184); 
    doc.text(`${year}`, padding + overlayX, overlayY + 35);

    const gridWidth = (pW - (padding * 2)) * 0.6;
    const startX = pW - padding - gridWidth + overlayX;
    const gridStartY = overlayY + 15;
    
    drawPDFGrid(doc, month, year, startX, gridStartY, gridWidth / 7, 8);
};

const renderSidebarPDF = (doc: jsPDF, month: string, year: number, pW: number, pH: number, offX: number, offY: number) => {
    const overlayWidth = pW * 0.25;
    const baseOverlayX = pW - overlayWidth;
    const overlayX = baseOverlayX + offX;
    const overlayY = offY;

    doc.setFillColor(15, 23, 42); 
    doc.rect(overlayX, 0, overlayWidth, pH, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(32);
    doc.text(month.substr(0, 3).toUpperCase(), overlayX + (overlayWidth/2), overlayY + 40, { align: 'center' });

    doc.setFontSize(18);
    doc.setTextColor(148, 163, 184);
    doc.text(`${year}`, overlayX + (overlayWidth/2), overlayY + 50, { align: 'center' });

    const gridWidth = overlayWidth * 0.8;
    const startX = overlayX + (overlayWidth * 0.1);
    const startY = overlayY + 80;
    
    drawPDFGrid(doc, month, year, startX, startY, gridWidth / 7, 12);
};

const renderMinimalPDF = (doc: jsPDF, month: string, year: number, pW: number, pH: number, offX: number, offY: number) => {
    const y = pH * 0.85 + offY;
    const x = offX;
    
    doc.setFillColor(0, 0, 0); 
    doc.rect(0, pH * 0.7, pW, pH * 0.3, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text(`${month} ${year}`, x + 15, y + 15);

    const gridWidth = pW * 0.5;
    drawPDFGrid(doc, month, year, x + pW - gridWidth - 10, y - 5, gridWidth / 7, 6);
};

const renderHeaderGridPDF = (doc: jsPDF, month: string, year: number, pW: number, pH: number, offX: number, offY: number) => {
    const y = offY;
    const x = offX;

    doc.setFillColor(0, 0, 0); 
    doc.rect(x, y, pW, pH * 0.15, "F");
    
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text(`${month} ${year}`, x + pW/2, y + pH * 0.1, { align: 'center' });

    const gridY = y + pH * 0.15;
    doc.setGState(new doc.GState({ opacity: 0.4 }));
    doc.rect(x, gridY, pW, pH * 0.5, "F");
    doc.setGState(new doc.GState({ opacity: 1.0 }));

    drawPDFGrid(doc, month, year, x + pW * 0.1, gridY + 5, (pW * 0.8) / 7, 15);
};

const drawPDFGrid = (doc: jsPDF, month: string, year: number, startX: number, startY: number, cellWidth: number, lineHeight: number) => {
    const daysOfWeek = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'];
    
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.setFont("helvetica", "bold");
    
    daysOfWeek.forEach((day, i) => {
      doc.text(day, startX + (i * cellWidth) + (cellWidth/2), startY, { align: "center" });
    });

    doc.setFont("helvetica", "normal");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);

    const monthIndex = MONTHS.indexOf(month);
    const date = new Date(year, monthIndex, 1);
    const firstDayIndex = date.getDay(); 
    const daysInMonth = new Date(year, monthIndex + 1, 0).getDate();

    let currentDay = 1;
    let currentRow = 1;

    for (let row = 0; row < 6; row++) {
      for (let col = 0; col < 7; col++) {
        if (row === 0 && col < firstDayIndex) continue;
        if (currentDay > daysInMonth) break;

        const xPos = startX + (col * cellWidth) + (cellWidth/2);
        const yPos = startY + (currentRow * lineHeight) + 2;

        doc.text(currentDay.toString(), xPos, yPos, { align: "center" });
        currentDay++;
      }
      if (currentDay > daysInMonth) break;
      currentRow++;
    }
};